# In Class Notebook, Week 06

You can always access the URL of this notebook: https://github.com/UIUC-iSchool-DataViz/is445_oauoag_fall2022/blob/master/week06/inClass_week06.ipynb 

Or post the URL into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
# import usual things
import pandas as pd
import bqplot
import numpy as np
import ipywidgets
import matplotlib.pyplot as plt

## Bit of a review from last class

In [2]:
# 1. data
data = np.random.random((10,10))

In [4]:
data.shape

(10, 10)

In [5]:
bqplot.ColorScale?

In [6]:
# 2. Scales
col_sc = bqplot.ColorScale()

In [7]:
# 3. Axis -- skip this for right now

In [8]:
bqplot.GridHeatMap?

In [9]:
# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

In [10]:
# 5. interactions -- skip for now as well

In [11]:
# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.18102…

In [12]:
# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')

# 3. Axis -- skip this for right now

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. interactions -- skip for now as well

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.18102…

In [13]:
bqplot.ColorAxis?

In [14]:
# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. interactions -- skip for now as well

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right')], fig_margin={…

In [16]:
# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc})

# 5. interactions -- skip for now as well

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [17]:
# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

{'name': 'selected', 'old': array([[0, 1]]), 'new': array([[5, 4]]), 'owner': GridHeatMap(color=array([[0.18102868, 0.05454827, 0.14790733, 0.24162776, 0.11821291,
        0.98108491, 0.67358506, 0.84167553, 0.38159203, 0.24736005],
       [0.87248269, 0.7496281 , 0.12147046, 0.49768312, 0.8150258 ,
        0.84724483, 0.97449228, 0.66123065, 0.98790992, 0.7264286 ],
       [0.62746968, 0.08201504, 0.3693932 , 0.69243688, 0.78808482,
        0.34686901, 0.09467904, 0.07534954, 0.1984768 , 0.15453815],
       [0.41372284, 0.76606028, 0.10728713, 0.76982562, 0.29883832,
        0.44449593, 0.22529206, 0.30030013, 0.1757342 , 0.06823544],
       [0.51601169, 0.21122179, 0.49987912, 0.25488668, 0.31463904,
        0.29469691, 0.7317339 , 0.94535344, 0.68825464, 0.67533604],
       [0.37748986, 0.10920031, 0.51901313, 0.82776109, 0.7392613 ,
        0.79730977, 0.54152581, 0.12177239, 0.73828878, 0.97627915],
       [0.56743095, 0.0384332 , 0.80993883, 0.82310542, 0.47688216,
        0.1425

In [18]:
heat_map.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'anchor_style',
 'apply_clip',
 'color',
 'column',
 'column_align',
 'display_format',
 'display_legend',
 'enable_hover',
 'font_style',
 'interactions',
 'labels',
 'null_color',
 'opacity',
 'preserve_domain',
 'row',
 'row_align',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [20]:
heat_map.selected

array([[0, 1]])

In [21]:
def on_selected(change):
    print(change)

In [22]:
heat_map.observe(on_selected,'selected')

In [23]:
def on_selected(change):
    print(change['owner'].selected)

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

[[2 4]]
[[2 3]]
[[0 3]]
[[3 2]]
[[3 3]
 [3 2]]
[[2 3]
 [2 2]
 [3 2]
 [3 3]]
[[1 2]
 [2 2]
 [3 2]]
[[0 5]]


In [24]:
def on_selected(change):
    if len(change['owner'].selected)==1: # only do things if I select a single cell
        print(change['owner'].selected[0])

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

[3 2]
[2 3]
[1 3]
[3 5]
[3 3]
[5 2]
[3 1]
[2 3]
[2 5]
[2 6]


In [25]:
myLabel = ipywidgets.Label()

In [26]:
myLabel

Label(value='')

In [27]:
def on_selected(change):
    if len(change['owner'].selected)==1: # only do things if I select a single cell
        #print(change['owner'].selected[0])
        i,j =change['owner'].selected[0]
        v = data[i,j]
        myLabel.value = 'Data value=' + str(v)

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [29]:
def on_selected(change):
    if len(change['owner'].selected)==1: # only do things if I select a single cell
        #print(change['owner'].selected[0])
        i,j =change['owner'].selected[0]
        v = data[i,j]
        myLabel.value = 'Data value=' + str(v)

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
#fig
myDashboard = ipywidgets.VBox([myLabel,fig])
myDashboard

## Multidimension (3D) data

In [30]:
data3d = np.random.random((10,10,20))

In [31]:
data3d.shape

(10, 10, 20)

In [33]:
i,j=0,0
data3d[i,j,:]

array([0.99567703, 0.7045831 , 0.74803011, 0.89077038, 0.61519606,
       0.02119523, 0.483597  , 0.85513086, 0.14595   , 0.88418687,
       0.79181803, 0.48996093, 0.811503  , 0.27361417, 0.88618678,
       0.43575293, 0.84712053, 0.49017694, 0.836867  , 0.68253888])

In [34]:
data3d[i,j,:].mean()

0.6444927914347501

In [36]:
data3d.mean(axis=2).shape

(10, 10)

In [37]:
def on_selected(change):
    if len(change['owner'].selected)==1: # only do things if I select a single cell
        i,j =change['owner'].selected[0]
        v = data3d[i,j,:].mean()
        myLabel.value = 'Mean data value=' + str(v)

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2), 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
#fig
myDashboard = ipywidgets.VBox([myLabel,fig])
myDashboard

In [38]:
# 1. data for histogram
i,j = 0,0
data3d[i,j]

array([0.99567703, 0.7045831 , 0.74803011, 0.89077038, 0.61519606,
       0.02119523, 0.483597  , 0.85513086, 0.14595   , 0.88418687,
       0.79181803, 0.48996093, 0.811503  , 0.27361417, 0.88618678,
       0.43575293, 0.84712053, 0.49017694, 0.836867  , 0.68253888])

In [39]:
# 2. scales for histogram
x_sch = bqplot.LinearScale() # numerical, no reason to take log
y_sch = bqplot.LinearScale()

In [40]:
# 3. Axis for histogram
x_axh = bqplot.Axis(scale=x_sch, label='Value of 3rd Axis')
y_axh = bqplot.Axis(scale=y_sch, label='Frequency', orientation='vertical')

In [42]:
bqplot.Hist?

In [43]:
hist = bqplot.Hist(sample=data3d[i,j,:],
                  scales={'sample':x_sch,'count':y_sch}, bins=5)

In [44]:
# put it all together in a histogram
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value of 3rd Axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', orie…

In [45]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [46]:
hist.sample

array([0.99567703, 0.7045831 , 0.74803011, 0.89077038, 0.61519606,
       0.02119523, 0.483597  , 0.85513086, 0.14595   , 0.88418687,
       0.79181803, 0.48996093, 0.811503  , 0.27361417, 0.88618678,
       0.43575293, 0.84712053, 0.49017694, 0.836867  , 0.68253888])

In [49]:
def on_selected(change):
    if len(change['owner'].selected)==1: # only do things if I select a single cell
        i,j =change['owner'].selected[0]
        v = data3d[i,j,:].mean()
        myLabel.value = 'Mean data value=' + str(v)
        # add update for histogram
        hist.sample = data3d[i,j,:]

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2), 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
#fig
#myDashboard = ipywidgets.VBox([myLabel,fig])
#myDashboard

In [50]:
# put the label on top, figures on the bottom
figures = ipywidgets.HBox([fig, figh])

myDashboard = ipywidgets.VBox([myLabel, figures])
myDashboard

In [51]:
fig.layout.min_width='500px'
figh.layout.min_width='500px'

## "Real" data dashboard with the UFOs dataset

In [52]:
data_url = 'https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/main/data/ufo-scrubbed-geocoded-time-standardized-00.csv'
ufos = pd.read_csv(data_url,
                  names = ["date", "city", "state", "country",
                          "shape", "duration_seconds", "duration",
                          "comment", "report_date", 
                           "latitude", "longitude"],
                  parse_dates = ["date", "report_date"])

In [53]:
ufos.head()

date                  city state country     shape  \
0 1949-10-10 20:30:00            san marcos    tx      us  cylinder   
1 1949-10-10 21:00:00          lackland afb    tx     NaN     light   
2 1955-10-10 17:00:00  chester (uk/england)   NaN      gb    circle   
3 1956-10-10 21:00:00                  edna    tx      us    circle   
4 1960-10-10 20:00:00               kaneohe    hi      us     light   

   duration_seconds    duration  \
0            2700.0  45 minutes   
1            7200.0     1-2 hrs   
2              20.0  20 seconds   
3              20.0    1/2 hour   
4             900.0  15 minutes   

                                             comment report_date   latitude  \
0  This event took place in early fall around 194...  2004-04-27  29.883056   
1  1949 Lackland AFB&#44 TX.  Lights racing acros...  2005-12-16  29.384210   
2  Green/Orange circular disc over Chester&#44 En...  2008-01-21  53.200000   
3  My older brother and twin sister were leaving ...  2004-01-17  28.978333   
4  AS a Marine 1st Lt. flying an FJ4B fighter/att...  2004-01-22  21.418056   

    longitude  
0  -97.941111  
1  -98.581082  
2   -2.916667  
3  -96.645833  
4 -157.803611

In [54]:
def generate_histogram_from_lat_long(ufos, nlong=20, nlat=20, longmin=-150, longmax=150,
                                     latmin=-40, latmax=70,
                                     takeLog=True):
    long_bins = np.linspace(longmin, longmax, nlong+1)
    lat_bins = np.linspace(latmin, latmax, nlat+1)
    hist2d, long_edges, lat_edges = np.histogram2d(ufos['longitude'], 
                                                   ufos['latitude'], 
                                                   weights=ufos['duration_seconds'],
                                                  bins = [long_bins,lat_bins])
    hist2d = hist2d.T
    if takeLog:
        hist2d[hist2d <= 0] = np.nan # set zeros to NaNs
        # then take log
        hist2d = np.log10(hist2d)
    long_centers = (long_edges[:-1] + long_edges[1:]) / 2
    lat_centers = (lat_edges[:-1] + lat_edges[1:]) / 2
    return hist2d, long_centers, lat_centers, long_edges, lat_edges

In [55]:
len(ufos)

80332

In [56]:
nsamples = 1000
downSampleMask = np.random.choice(range(len(ufos)-1),nsamples, replace=False)
downSampleMask

array([64155, 12979, 48970,   642, 59928, 78777, 61941, 77387, 77324,
       54952, 16359, 17918, 33260, 23558, 55254,  9585, 22485, 13349,
       62878, 56257, 42135, 33384, 43350, 12770, 27466, 33831, 51674,
       37324, 18664, 48198, 22517, 48189, 65358, 72268, 44023, 26760,
       48243, 50243, 28919, 10385,  3478, 50634, 15283, 43259, 30420,
       38445, 34068,  2126, 60990, 52019, 53703, 55598, 47058, 35073,
       34048, 47343, 63344,  4189, 33224, 33598,  8182, 56321, 65545,
        4942, 70456,  7083, 33298, 58093,  5792, 11618, 45701, 58669,
         375, 79201, 13491,  3101, 21224, 16767, 16731, 71614, 41021,
       17689, 43646,  2129, 50979,  3148, 60124, 62571, 10997, 53745,
       29786, 58955, 59881, 24111, 47267, 48771, 20061, 63019,  9316,
        2685, 18810, 30232, 65120, 49800, 67510, 16444, 70603, 63891,
       19538, 58001, 20273, 64124,  6617, 34190,  7319, 60953, 77792,
        2452, 25106, 57315, 44598, 59683, 14846, 67405, 39442, 75049,
       51688, 65359,

In [57]:
ufosDS = ufos.loc[downSampleMask]

In [58]:
len(ufosDS)

1000

In [60]:
# 2. scales 
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')

# 4. marks
scatters = bqplot.Scatter(x=ufosDS['longitude'], y =ufosDS['latitude'], 
                         scales={'x':x_sc, 'y':y_sc})

# all together now!
fig = bqplot.Figure(marks=[scatters], axes=[x_ax,y_ax])
fig

Figure(axes=[Axis(label='Longitude', scale=LinearScale()), Axis(label='Latitude', orientation='vertical', scal…

In [62]:
# 2. scales 
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')

# 4. marks
scatters = bqplot.Scatter(x=ufosDS['longitude'], y =ufosDS['latitude'], color=ufosDS['duration_seconds'],
                         scales={'x':x_sc, 'y':y_sc, 'color':col_sc})

# all together now!
fig = bqplot.Figure(marks=[scatters], axes=[x_ax,y_ax])
fig

Figure(axes=[Axis(label='Longitude', scale=LinearScale()), Axis(label='Latitude', orientation='vertical', scal…

In [63]:
ufosDS['duration_seconds'].min(), ufosDS['duration_seconds'].max()

(0.01, 52623200.0)

In [65]:
# 2. scales 
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, label='log10(sec)', 
                         orientation='vertical', side='right')

# 4. marks
scatters = bqplot.Scatter(x=ufosDS['longitude'], y =ufosDS['latitude'], color=np.log10(ufosDS['duration_seconds']),
                         scales={'x':x_sc, 'y':y_sc, 'color':col_sc})

# all together now!
fig = bqplot.Figure(marks=[scatters], axes=[x_ax,y_ax,col_ax])
fig

Figure(axes=[Axis(label='Longitude', scale=LinearScale()), Axis(label='Latitude', orientation='vertical', scal…

In [66]:
# 1. data
hist2d, long_centers, lat_centers, long_edges, lat_edges = generate_histogram_from_lat_long(ufos)

In [68]:
np.nanmin(hist2d), np.nanmax(hist2d)

(0.0, 8.09710747658943)

In [69]:
# 2. scales
col_sc = bqplot.ColorScale(scheme='RdPu', min=np.nanmin(hist2d), max=np.nanmax(hist2d))
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')

# 4. marks
heat_map = bqplot.GridHeatMap(color=hist2d, 
                             row=lat_centers, column=long_centers,
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions = {'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactivity -- skip for now!

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(max=8.09710747658943, min=0.0, scheme='RdPu'),…

In [73]:
myLabel = ipywidgets.Label()
def on_selected(change):
    if len(change['owner'].selected) == 1: # only selecting one bin at a time
        i,j = change['owner'].selected[0]
        v = hist2d[i,j]
        myLabel.value = 'Total duration in log10(sec)='+str(v)

# 2. scales
col_sc = bqplot.ColorScale(scheme='RdPu', min=np.nanmin(hist2d), max=np.nanmax(hist2d))
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')

# 4. marks
heat_map = bqplot.GridHeatMap(color=hist2d, 
                             row=lat_centers, column=long_centers,
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions = {'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactivity -- skip for now!
heat_map.observe(on_selected,'selected')

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig
myDashboard = ipywidgets.VBox([myLabel,fig])
myDashboard

In [74]:
import datetime as dt

In [91]:
# 1. data for scatter plot already there

# 2. scales
x_scl = bqplot.DateScale(min=dt.datetime(1950,1,1), max=dt.datetime(2022,1,1))
y_scl = bqplot.LogScale()

In [92]:
# 3. axis
x_ax = bqplot.Axis(label='Date', scale=x_scl)
y_ax = bqplot.Axis(label='Duration in Sec', scale=y_scl, orientation='vertical', side='left')

In [93]:
i,j=19,0

In [94]:
long_min = long_edges[j]
long_max = long_edges[j+1]

In [95]:
long_min, long_max

(-150.0, -135.0)

In [96]:
lat_min = lat_edges[i]
lat_max = lat_edges[i+1]

In [97]:
lat_min, lat_max

(64.5, 70.0)

In [98]:
region_mask = ( (ufos['latitude']>=lat_min) & (ufos['latitude']<=lat_max) & \
              (ufos['longitude']>=long_min) & (ufos['longitude']<=long_max) )

In [99]:
ufos['latitude'][region_mask]

327      64.837778
2845     64.837778
3620     64.837778
4602     64.751111
6011     64.837778
           ...    
77347    64.751111
77497    64.837778
78571    64.837778
79029    64.837778
79470    64.837778
Name: latitude, Length: 74, dtype: float64

In [100]:
ufos['longitude'][region_mask]

327     -147.716389
2845    -147.716389
3620    -147.716389
4602    -147.349444
6011    -147.716389
            ...    
77347   -147.349444
77497   -147.716389
78571   -147.716389
79029   -147.716389
79470   -147.716389
Name: longitude, Length: 74, dtype: float64

In [101]:
scatters = bqplot.Scatter(x=ufos['date'][region_mask], y=ufos['duration_seconds'][region_mask],
                         scales={'x':x_scl, 'y':y_scl})

In [102]:
fig_dur = bqplot.Figure(marks=[scatters], axes=[x_ax, y_ax])
fig_dur

Figure(axes=[Axis(label='Date', scale=DateScale(max=datetime.datetime(2022, 1, 1, 0, 0), min=datetime.datetime…

In [105]:
myLabel = ipywidgets.Label()
def on_selected(change):
    if len(change['owner'].selected) == 1: # only selecting one bin at a time
        i,j = change['owner'].selected[0]
        v = hist2d[i,j]
        myLabel.value = 'Total duration in log10(sec)='+str(v)
        # couple of steps to update the scatter plot
        long_min = long_edges[j]
        long_max = long_edges[j+1]
        lat_min = lat_edges[i]
        lat_max = lat_edges[i+1]
        region_mask = ( (ufos['latitude']>=lat_min) & (ufos['latitude']<=lat_max) & \
              (ufos['longitude']>=long_min) & (ufos['longitude']<=long_max) )
        scatters.x = ufos['date'][region_mask]
        scatters.y = ufos['duration_seconds'][region_mask]
        

# 2. scales
col_sc = bqplot.ColorScale(scheme='RdPu', min=np.nanmin(hist2d), max=np.nanmax(hist2d))
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')

# 4. marks
heat_map = bqplot.GridHeatMap(color=hist2d, 
                             row=lat_centers, column=long_centers,
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions = {'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactivity -- skip for now!
heat_map.observe(on_selected,'selected')

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig
#myDashboard = ipywidgets.VBox([myLabel,fig])
fig.layout.min_width='500px'
fig_dur.layout.min_width='500px'
figures = ipywidgets.HBox([fig,fig_dur])
myDashboard = ipywidgets.VBox([myLabel,figures])
myDashboard

In [106]:
# 1. data for barplot
i,j=19,0

In [107]:
ufos.columns

Index(['date', 'city', 'state', 'country', 'shape', 'duration_seconds',
       'duration', 'comment', 'report_date', 'latitude', 'longitude'],
      dtype='object')

In [108]:
ufos['year'] = ufos['date'].dt.year

In [109]:
ufos['year']

0        1949
1        1949
2        1955
3        1956
4        1960
         ... 
80327    2013
80328    2013
80329    2013
80330    2013
80331    2013
Name: year, Length: 80332, dtype: int64

In [110]:
# couple of steps to update the scatter plot
long_min = long_edges[j]
long_max = long_edges[j+1]
lat_min = lat_edges[i]
lat_max = lat_edges[i+1]
region_mask = ( (ufos['latitude']>=lat_min) & (ufos['latitude']<=lat_max) & \
      (ufos['longitude']>=long_min) & (ufos['longitude']<=long_max) )

In [ ]:
dur, dur_edgets