# In Class Notebook, Week 06

You can always access the URL of this notebook: https://github.com/UIUC-iSchool-DataViz/is445_oauoag_fall2022/blob/master/week06/inClass_week06.ipynb 

Or post the URL into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
# import usual things
import pandas as pd
import bqplot
import numpy as np
import ipywidgets
import matplotlib.pyplot as plt

## Bit of a review from last class

In [2]:
# 1. data
data = np.random.random((10,10))

In [4]:
data.shape

(10, 10)

In [5]:
bqplot.ColorScale?

In [6]:
# 2. Scales
col_sc = bqplot.ColorScale()

In [7]:
# 3. Axis -- skip this for right now

In [8]:
bqplot.GridHeatMap?

In [9]:
# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

In [10]:
# 5. interactions -- skip for now as well

In [11]:
# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.18102…

In [12]:
# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')

# 3. Axis -- skip this for right now

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. interactions -- skip for now as well

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.18102…

In [13]:
bqplot.ColorAxis?

In [14]:
# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. interactions -- skip for now as well

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right')], fig_margin={…

In [16]:
# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc})

# 5. interactions -- skip for now as well

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [17]:
# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

{'name': 'selected', 'old': array([[0, 1]]), 'new': array([[5, 4]]), 'owner': GridHeatMap(color=array([[0.18102868, 0.05454827, 0.14790733, 0.24162776, 0.11821291,
        0.98108491, 0.67358506, 0.84167553, 0.38159203, 0.24736005],
       [0.87248269, 0.7496281 , 0.12147046, 0.49768312, 0.8150258 ,
        0.84724483, 0.97449228, 0.66123065, 0.98790992, 0.7264286 ],
       [0.62746968, 0.08201504, 0.3693932 , 0.69243688, 0.78808482,
        0.34686901, 0.09467904, 0.07534954, 0.1984768 , 0.15453815],
       [0.41372284, 0.76606028, 0.10728713, 0.76982562, 0.29883832,
        0.44449593, 0.22529206, 0.30030013, 0.1757342 , 0.06823544],
       [0.51601169, 0.21122179, 0.49987912, 0.25488668, 0.31463904,
        0.29469691, 0.7317339 , 0.94535344, 0.68825464, 0.67533604],
       [0.37748986, 0.10920031, 0.51901313, 0.82776109, 0.7392613 ,
        0.79730977, 0.54152581, 0.12177239, 0.73828878, 0.97627915],
       [0.56743095, 0.0384332 , 0.80993883, 0.82310542, 0.47688216,
        0.1425

In [18]:
heat_map.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'anchor_style',
 'apply_clip',
 'color',
 'column',
 'column_align',
 'display_format',
 'display_legend',
 'enable_hover',
 'font_style',
 'interactions',
 'labels',
 'null_color',
 'opacity',
 'preserve_domain',
 'row',
 'row_align',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [20]:
heat_map.selected

array([[0, 1]])

In [21]:
def on_selected(change):
    print(change)

In [22]:
heat_map.observe(on_selected,'selected')

In [23]:
def on_selected(change):
    print(change['owner'].selected)

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

[[2 4]]
[[2 3]]
[[0 3]]
[[3 2]]
[[3 3]
 [3 2]]
[[2 3]
 [2 2]
 [3 2]
 [3 3]]
[[1 2]
 [2 2]
 [3 2]]
[[0 5]]


In [24]:
def on_selected(change):
    if len(change['owner'].selected)==1: # only do things if I select a single cell
        print(change['owner'].selected[0])

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

[3 2]
[2 3]
[1 3]
[3 5]
[3 3]
[5 2]
[3 1]
[2 3]
[2 5]
[2 6]


In [25]:
myLabel = ipywidgets.Label()

In [26]:
myLabel

Label(value='')

In [27]:
def on_selected(change):
    if len(change['owner'].selected)==1: # only do things if I select a single cell
        #print(change['owner'].selected[0])
        i,j =change['owner'].selected[0]
        v = data[i,j]
        myLabel.value = 'Data value=' + str(v)

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [29]:
def on_selected(change):
    if len(change['owner'].selected)==1: # only do things if I select a single cell
        #print(change['owner'].selected[0])
        i,j =change['owner'].selected[0]
        v = data[i,j]
        myLabel.value = 'Data value=' + str(v)

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data, 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
#fig
myDashboard = ipywidgets.VBox([myLabel,fig])
myDashboard

## Multidimension (3D) data

In [30]:
data3d = np.random.random((10,10,20))

In [31]:
data3d.shape

(10, 10, 20)

In [33]:
i,j=0,0
data3d[i,j,:]

array([0.99567703, 0.7045831 , 0.74803011, 0.89077038, 0.61519606,
       0.02119523, 0.483597  , 0.85513086, 0.14595   , 0.88418687,
       0.79181803, 0.48996093, 0.811503  , 0.27361417, 0.88618678,
       0.43575293, 0.84712053, 0.49017694, 0.836867  , 0.68253888])

In [34]:
data3d[i,j,:].mean()

0.6444927914347501

In [36]:
data3d.mean(axis=2).shape

(10, 10)

In [37]:
def on_selected(change):
    if len(change['owner'].selected)==1: # only do things if I select a single cell
        i,j =change['owner'].selected[0]
        v = data3d[i,j,:].mean()
        myLabel.value = 'Mean data value=' + str(v)

# 2. Scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- skip this for right now
col_ax = bqplot.ColorAxis(scale=col_sc, 
                         orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- grid heatmap
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2), 
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# 5. interactions -- skip for now as well
heat_map.observe(on_selected,'selected')

# put it all together as a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax,y_ax])
#fig
myDashboard = ipywidgets.VBox([myLabel,fig])
myDashboard